version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - echo "Building Docker image..."
      - docker build -t react_aws . 
      - docker tag react_aws:latest <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/react_aws:latest
      - echo "Pushing image to ECR..."
      - docker push <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/react_aws:latest

artifacts:
  files:
    - '**/*'
